name: thebags_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1

  webview_flutter: ^4.0.1
  flutter_html: ^3.0.0-alpha.5
  cached_network_image: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.17.0
  fluttertoast: ^8.2.5

  
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
  assets:
    - assets/imgs/onboard-background.png
    - assets/imgs/logo-thebags.png
    - assets/imgs/logo-hive.png
    - assets/imgs/profile-screen-avatar.jpg
    - assets/imgs/profile-screen-bg.png
    - assets/imgs/register-bg.png
    - assets/imgs/argon-logo.png
    - assets/imgs/venus-logo.png
    - assets/imgs/dining_tab.png
    - assets/imgs/cash.png
    - assets/imgs/paypal.png
    - assets/imgs/vnpay.png